node {    
    def app     
    stage('Clone repository') {               
             
        checkout scm    
    }     
    stage('Build image') {         
       
        app = docker.build("testcloudrun-313619")    
    }     
    stage('Test image') {           
        app.inside {            
            sh 'echo "Tests passed"'        
        }    
    }     
    stage('Push image') {
        docker.withRegistry('https://us.gcr.io/', 'gcr') {            
            app.push("${env.BUILD_NUMBER}")            
            app.push("latest")        
        }    
    }
}