node {    
    def app     
    stage('Clone repository') {               
             
        checkout scm    
    }     
    stage('Build image') {         
       
        app = docker.build("ekarniybabay/deno-cloudrun")    
    }     
    stage('Test image') {           
        app.inside {            
            sh 'echo "Tests passed"'        
        }    
    }     
    stage('Push image') {
        docker.withRegistry('https://registry.hub.docker.com', 'dochub') {            
            app.push("${env.BUILD_NUMBER}")            
            app.push("latest")        
        }    
    }
}